version: '3.8'
services:
  db:
    image: mysql
    container_name: fakeapi
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: fakeapi
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
