version: '3.8'

services:
  api:
    container_name: mocker-api
    restart: always
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    env_file:
      - .env.development
    command: npm run start:dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - mocker-network
  database:
    image: postgres
    container_name: mocker-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mocker
    ports:
      - "5432:5432"
    volumes:
      - /:/data/postgres
    networks:
      - mocker-network

networks:
  mocker-network:
    driver: bridge
